name: validate-yaml 
on:
  push:
    paths:
      - "*.yaml"
    branches:
      - main
  pull_request:
    paths:
      - "*.yaml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  syntax-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: check syntax
        id: json-yaml-validate
        uses: GrantBirki/json-yaml-validate@v2.6.2
        with:
          use_dot_match: false
          files: "ssh_keys.yaml"
  schema-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: check schema
        uses: nrkno/yaml-schema-validator-github-action@v5.0.0
        with:
          schema: _schema.yaml
          target: ssh_keys.yaml
